os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - |
        cd src
        docker build -t vcity:vallee-chimie ud-viz-context 
    - stage: "Markdown link checks"
      language: node_js
      node_js: 12
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=1
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi
