os: linux
dist: focal
language: node_js
node_js: 
    - 15

before_install:
    - npm --version

jobs:
  include:
    - stage: build
      script:
      - npm install
      - npm run travis
    - stage: "Markdown link checks"
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=1
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi
